version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:alpine

  django:
    container_name: django
    build:
      context: ./demo_celery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./demo_celery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0#$9184jfsljf928342904
      - ALLOWED_HOSTS=localhost,127.0.01
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./demo_celery
    command: celery --app=demo_celery worker -l INFO
    volumes:
      - ./demo_celery:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0#$9184jfsljf928342904
      - ALLOWED_HOSTS=localhost,127.0.01
    depends_on:
      - redis
